import { describe, expect, it, vi } from 'vitest';
import { screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import PostSummarizer from '@/features/posts/components/PostSummarizer';
import { apiCall } from '@/lib/http/client';
import { deferred, fail, ok, renderWithClient } from '@/test/utils';

vi.mock('@/lib/http/client', () => ({ apiCall: vi.fn(), apiUpload: vi.fn() }));
const apiCallMock = vi.mocked(apiCall);

const summary = { summary: 'A concise summary.', tags: ['nestjs', 'api'], source: 'model', truncated: false };

describe('PostSummarizer', () => {
  it('starts idle with a prompt and an enabled button', () => {
    renderWithClient(<PostSummarizer postId="p1" />);
    expect(screen.getByText('Get a short summary and skill tags for this post.')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Summarize' })).toBeEnabled();
  });

  it('shows a loading state, ignores repeat clicks and then renders the result', async () => {
    const user = userEvent.setup();
    const pending = deferred<any>();
    apiCallMock.mockReturnValue(pending.promise);
    renderWithClient(<PostSummarizer postId="p1" />);

    await user.click(screen.getByRole('button', { name: 'Summarize' }));
    const busy = await screen.findByRole('button', { name: 'Summarizing...' });
    expect(busy).toBeDisabled();
    expect(busy).toHaveAttribute('aria-busy', 'true');
    expect(screen.getByRole('status')).toBeInTheDocument();
    await user.click(busy);
    expect(apiCallMock).toHaveBeenCalledTimes(1);

    pending.resolve(ok(summary));
    expect(await screen.findByText('A concise summary.')).toBeInTheDocument();
    expect(screen.getByText('nestjs')).toBeInTheDocument();
    expect(screen.getByText('api')).toBeInTheDocument();
    expect(screen.getByText(/Generated by an AI model/)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Summarize again' })).toBeEnabled();
  });

  it('labels mock summaries and notes truncation', async () => {
    const user = userEvent.setup();
    apiCallMock.mockResolvedValue(ok({ ...summary, source: 'mock', truncated: true, tags: [] }));
    renderWithClient(<PostSummarizer postId="p1" />);

    await user.click(screen.getByRole('button', { name: 'Summarize' }));

    expect(await screen.findByText(/built-in demo summarizer/)).toBeInTheDocument();
    expect(screen.getByText(/only the first 4[,.]?000 characters were summarized/)).toBeInTheDocument();
    expect(screen.getByText('No tags were generated.')).toBeInTheDocument();
  });

  it('shows a non-retryable error without a retry button', async () => {
    const user = userEvent.setup();
    apiCallMock.mockResolvedValue(fail('This post is too short to summarize.', 422));
    renderWithClient(<PostSummarizer postId="p1" />);

    await user.click(screen.getByRole('button', { name: 'Summarize' }));

    expect(await screen.findByRole('alert')).toHaveTextContent('This post is too short to summarize.');
    expect(screen.queryByRole('button', { name: 'Retry' })).not.toBeInTheDocument();
  });

  it('shows a retryable error and recovers on retry', async () => {
    const user = userEvent.setup();
    apiCallMock.mockResolvedValueOnce(fail('Summarizer unavailable', 503)).mockResolvedValueOnce(ok(summary));
    renderWithClient(<PostSummarizer postId="p1" />);

    await user.click(screen.getByRole('button', { name: 'Summarize' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('Summarizer unavailable');

    await user.click(screen.getByRole('button', { name: 'Retry' }));
    expect(await screen.findByText('A concise summary.')).toBeInTheDocument();
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
    expect(apiCallMock).toHaveBeenCalledTimes(2);
  });
});
