'use client';
import { useRef } from 'react';
import { AlertCircle, RotateCw, Sparkles } from 'lucide-react';
import { useSummarizePost } from '@/features/posts/mutations/posts';

interface PostSummarizerProps {
  postId: string;
}

const INPUT_LIMIT = 4000;

export default function PostSummarizer({ postId }: PostSummarizerProps) {
  const mutation = useSummarizePost(postId);
  const lockRef = useRef(false);
  const isPending = mutation.isPending;
  const result = mutation.isSuccess ? mutation.data : null;
  const error = mutation.isError ? mutation.error : null;

  const run = () => {
    if (lockRef.current || mutation.isPending) return;
    lockRef.current = true;
    mutation.mutate(undefined, {
      onSettled: () => {
        lockRef.current = false;
      },
    });
  };

  return (
    <section aria-labelledby="post-summary-title" className="mb-4 rounded-lg border border-slate-200 bg-white p-5 sm:p-6">
      <div className="flex items-center justify-between gap-3">
        <h2 id="post-summary-title" className="inline-flex items-center gap-2 text-base font-semibold text-slate-900">
          <Sparkles size={16} className="text-brand" />
          AI summary
        </h2>
        {!error && (
          <button
            type="button"
            onClick={run}
            disabled={isPending}
            aria-busy={isPending}
            className="inline-flex items-center gap-1.5 rounded-lg bg-brand px-4 py-1.5 text-sm font-semibold text-white transition hover:bg-brand-dark disabled:opacity-60"
          >
            {result && !isPending && <RotateCw size={14} />}
            {isPending ? 'Summarizing...' : result ? 'Summarize again' : 'Summarize'}
          </button>
        )}
      </div>

      <div aria-live="polite" className="mt-4">
        {!isPending && !result && !error && (
          <p className="text-sm text-slate-500">Get a short summary and skill tags for this post.</p>
        )}

        {isPending && (
          <div className="animate-pulse space-y-2" role="status">
            <span className="sr-only">Summarizing this post</span>
            <div className="h-3 w-full rounded bg-slate-200" />
            <div className="h-3 w-5/6 rounded bg-slate-200" />
            <div className="h-3 w-2/3 rounded bg-slate-200" />
          </div>
        )}

        {!isPending && error && (
          <div role="alert" className="rounded-lg border border-red-100 bg-red-50 p-4">
            <p className="flex items-start gap-2 text-sm font-medium text-red-700">
              <AlertCircle size={16} className="mt-0.5 shrink-0" />
              <span className="min-w-0 break-words">{error.message}</span>
            </p>
            {error.retryable && (
              <button
                type="button"
                onClick={run}
                disabled={isPending}
                className="mt-3 inline-flex items-center gap-1.5 rounded-lg bg-red-600 px-3 py-1.5 text-sm font-semibold text-white hover:bg-red-700 disabled:opacity-60"
              >
                <RotateCw size={14} />
                Retry
              </button>
            )}
          </div>
        )}

        {!isPending && result && (
          <div>
            <p className="min-w-0 break-words text-sm leading-relaxed text-slate-700">{result.summary}</p>
            {result.tags.length > 0 ? (
              <ul className="mt-3 flex flex-wrap gap-2" aria-label="Skill tags">
                {result.tags.map((tag) => (
                  <li key={tag} className="rounded-full bg-brand/10 px-3 py-1 text-xs font-medium text-brand">
                    {tag}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="mt-3 text-xs text-slate-400">No tags were generated.</p>
            )}
            {result.truncated && (
              <p className="mt-3 text-xs text-slate-500">
                This post is long, so only the first {INPUT_LIMIT.toLocaleString()} characters were summarized.
              </p>
            )}
            <p className="mt-3 text-xs text-slate-400">
              {result.source === 'mock'
                ? 'Generated by the built-in demo summarizer (no AI model configured). It may be inaccurate.'
                : 'Generated by an AI model. It may be inaccurate, so check the full post.'}
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
